defaultSettings:
  defaultReplicaCount: 1
  deletingConfirmationFlag: true

persistence:
  defaultClass: true
  defaultClassReplicaCount: 1

longhornUI:
  replicas: 1

preUpgradeChecker:
  jobEnabled: false
