apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-database-mariadb
  namespace: argocd

spec:
  project: default

  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: mariadb
      targetRevision: 23.0.4
      helm:
        valueFiles:
          - $values/platform/database/mariadb/values.yaml

    - repoURL: https://github.com/Axelsson2000/onc.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: platform-database

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
