apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-database-mariadb-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"

spec:
  project: default

  source:
    repoURL: https://github.com/Axelsson2000/onc.git
    targetRevision: main
    path: platform/database/mariadb/resources

  destination:
    server: https://kubernetes.default.svc
    namespace: platform-database

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
