apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-infrastructure-headlamp
  namespace: argocd

spec:
  project: default

  sources:
    - repoURL: https://kubernetes-sigs.github.io/headlamp/
      chart: headlamp
      targetRevision: 0.35.0
      helm:
        valueFiles:
          - $values/applications/infrastructure/headlamp/values.yaml

    - repoURL: https://github.com/Axelsson2000/onc.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
