ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: headlamp.onc.local
      paths:
        - path: /
          type: Prefix

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
