nextcloud:
  host: nextcloud.onc.local
  username: admin
  password: Nextcloud123!

  configs:
    trusted_domains.config.php: |-
      <?php
      $CONFIG = array (
        'trusted_domains' =>
        array (
          0 => 'nextcloud.onc.local',
        ),
      );

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: mysql
  host: platform-database-mariadb.platform-database.svc.cluster.local
  database: nextcloud
  user: nextcloud
  password: nextcloudpassword

mariadb:
  enabled: false

postgresql:
  enabled: false

persistence:
  enabled: true
  storageClass: longhorn
  size: 20Gi

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: nextcloud.onc.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 2Gi
