fullnameOverride: platform-prometheus

grafana:
  enabled: true

  adminUser: admin
  adminPassword: admin

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.onc.local
    path: /
    pathType: Prefix

  persistence:
    enabled: true
    type: pvc
    size: 5Gi
    accessModes:
      - ReadWriteOnce

prometheus:
  enabled: true

  prometheusSpec:
    retention: 3d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi

alertmanager:
  enabled: true

  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  enabled: true
